version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true