name: 'DeepSource'
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_VERSION: '10.0.x' # set this to the dotnet version to use

jobs:
  analyze:
    name: 'DeepSource'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Setup DotNet ${{ env.DOTNET_VERSION }} Environment'
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Install dotnet-coverage'
        run: |
          dotnet tool install --global dotnet-coverage

      - name: 'Restore Solution Dependencies'
        run: |
          dotnet restore
          
      - name: 'Build Solution'
        run: |
          dotnet build --configuration Release --no-restore

      - name: 'Run Unit Tests'
        run: |
          dotnet-coverage collect 'dotnet test --configuration Release --no-build --no-restore --logger:"console;verbosity=detailed"' -f cobertura -o 'coverage.cobertura.xml'

      - name: 'Send Coverage Report to DeepSource'
        uses: deepsourcelabs/test-coverage-action@4284bb73a04adb39faaa6bfcc2d0e3dd137ffed7 # v1.1.3
        with:
          key: csharp
          coverage-file: coverage.cobertura.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
          fail-ci-on-error: true
